// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: pong.proto

package pong

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PongAuth_RequestNonce_FullMethodName = "/pong.PongAuth/RequestNonce"
	PongAuth_VerifyLogin_FullMethodName  = "/pong.PongAuth/VerifyLogin"
)

// PongAuthClient is the client API for PongAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Wallet authentication (Decred signmessage over gRPC)
type PongAuthClient interface {
	// Request a one-time nonce to sign in the wallet
	RequestNonce(ctx context.Context, in *RequestNonceRequest, opts ...grpc.CallOption) (*RequestNonceResponse, error)
	// Verify a wallet signature and establish a session
	VerifyLogin(ctx context.Context, in *VerifyLoginRequest, opts ...grpc.CallOption) (*VerifyLoginResponse, error)
}

type pongAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewPongAuthClient(cc grpc.ClientConnInterface) PongAuthClient {
	return &pongAuthClient{cc}
}

func (c *pongAuthClient) RequestNonce(ctx context.Context, in *RequestNonceRequest, opts ...grpc.CallOption) (*RequestNonceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestNonceResponse)
	err := c.cc.Invoke(ctx, PongAuth_RequestNonce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pongAuthClient) VerifyLogin(ctx context.Context, in *VerifyLoginRequest, opts ...grpc.CallOption) (*VerifyLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyLoginResponse)
	err := c.cc.Invoke(ctx, PongAuth_VerifyLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PongAuthServer is the server API for PongAuth service.
// All implementations must embed UnimplementedPongAuthServer
// for forward compatibility.
//
// Wallet authentication (Decred signmessage over gRPC)
type PongAuthServer interface {
	// Request a one-time nonce to sign in the wallet
	RequestNonce(context.Context, *RequestNonceRequest) (*RequestNonceResponse, error)
	// Verify a wallet signature and establish a session
	VerifyLogin(context.Context, *VerifyLoginRequest) (*VerifyLoginResponse, error)
	mustEmbedUnimplementedPongAuthServer()
}

// UnimplementedPongAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPongAuthServer struct{}

func (UnimplementedPongAuthServer) RequestNonce(context.Context, *RequestNonceRequest) (*RequestNonceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestNonce not implemented")
}
func (UnimplementedPongAuthServer) VerifyLogin(context.Context, *VerifyLoginRequest) (*VerifyLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyLogin not implemented")
}
func (UnimplementedPongAuthServer) mustEmbedUnimplementedPongAuthServer() {}
func (UnimplementedPongAuthServer) testEmbeddedByValue()                  {}

// UnsafePongAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PongAuthServer will
// result in compilation errors.
type UnsafePongAuthServer interface {
	mustEmbedUnimplementedPongAuthServer()
}

func RegisterPongAuthServer(s grpc.ServiceRegistrar, srv PongAuthServer) {
	// If the following call pancis, it indicates UnimplementedPongAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PongAuth_ServiceDesc, srv)
}

func _PongAuth_RequestNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestNonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongAuthServer).RequestNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PongAuth_RequestNonce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongAuthServer).RequestNonce(ctx, req.(*RequestNonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PongAuth_VerifyLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongAuthServer).VerifyLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PongAuth_VerifyLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongAuthServer).VerifyLogin(ctx, req.(*VerifyLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PongAuth_ServiceDesc is the grpc.ServiceDesc for PongAuth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PongAuth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pong.PongAuth",
	HandlerType: (*PongAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestNonce",
			Handler:    _PongAuth_RequestNonce_Handler,
		},
		{
			MethodName: "VerifyLogin",
			Handler:    _PongAuth_VerifyLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pong.proto",
}

const (
	PongGame_SendInput_FullMethodName         = "/pong.PongGame/SendInput"
	PongGame_StartGameStream_FullMethodName   = "/pong.PongGame/StartGameStream"
	PongGame_StartNtfnStream_FullMethodName   = "/pong.PongGame/StartNtfnStream"
	PongGame_UnreadyGameStream_FullMethodName = "/pong.PongGame/UnreadyGameStream"
	PongGame_SignalReadyToPlay_FullMethodName = "/pong.PongGame/SignalReadyToPlay"
)

// PongGameClient is the client API for PongGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PongGameClient interface {
	// pong game
	SendInput(ctx context.Context, in *PlayerInput, opts ...grpc.CallOption) (*GameUpdate, error)
	StartGameStream(ctx context.Context, in *StartGameStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameUpdateBytes], error)
	StartNtfnStream(ctx context.Context, in *StartNtfnStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NtfnStreamResponse], error)
	UnreadyGameStream(ctx context.Context, in *UnreadyGameStreamRequest, opts ...grpc.CallOption) (*UnreadyGameStreamResponse, error)
	SignalReadyToPlay(ctx context.Context, in *SignalReadyToPlayRequest, opts ...grpc.CallOption) (*SignalReadyToPlayResponse, error)
}

type pongGameClient struct {
	cc grpc.ClientConnInterface
}

func NewPongGameClient(cc grpc.ClientConnInterface) PongGameClient {
	return &pongGameClient{cc}
}

func (c *pongGameClient) SendInput(ctx context.Context, in *PlayerInput, opts ...grpc.CallOption) (*GameUpdate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameUpdate)
	err := c.cc.Invoke(ctx, PongGame_SendInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pongGameClient) StartGameStream(ctx context.Context, in *StartGameStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameUpdateBytes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PongGame_ServiceDesc.Streams[0], PongGame_StartGameStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartGameStreamRequest, GameUpdateBytes]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PongGame_StartGameStreamClient = grpc.ServerStreamingClient[GameUpdateBytes]

func (c *pongGameClient) StartNtfnStream(ctx context.Context, in *StartNtfnStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NtfnStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PongGame_ServiceDesc.Streams[1], PongGame_StartNtfnStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartNtfnStreamRequest, NtfnStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PongGame_StartNtfnStreamClient = grpc.ServerStreamingClient[NtfnStreamResponse]

func (c *pongGameClient) UnreadyGameStream(ctx context.Context, in *UnreadyGameStreamRequest, opts ...grpc.CallOption) (*UnreadyGameStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnreadyGameStreamResponse)
	err := c.cc.Invoke(ctx, PongGame_UnreadyGameStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pongGameClient) SignalReadyToPlay(ctx context.Context, in *SignalReadyToPlayRequest, opts ...grpc.CallOption) (*SignalReadyToPlayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalReadyToPlayResponse)
	err := c.cc.Invoke(ctx, PongGame_SignalReadyToPlay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PongGameServer is the server API for PongGame service.
// All implementations must embed UnimplementedPongGameServer
// for forward compatibility.
type PongGameServer interface {
	// pong game
	SendInput(context.Context, *PlayerInput) (*GameUpdate, error)
	StartGameStream(*StartGameStreamRequest, grpc.ServerStreamingServer[GameUpdateBytes]) error
	StartNtfnStream(*StartNtfnStreamRequest, grpc.ServerStreamingServer[NtfnStreamResponse]) error
	UnreadyGameStream(context.Context, *UnreadyGameStreamRequest) (*UnreadyGameStreamResponse, error)
	SignalReadyToPlay(context.Context, *SignalReadyToPlayRequest) (*SignalReadyToPlayResponse, error)
	mustEmbedUnimplementedPongGameServer()
}

// UnimplementedPongGameServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPongGameServer struct{}

func (UnimplementedPongGameServer) SendInput(context.Context, *PlayerInput) (*GameUpdate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInput not implemented")
}
func (UnimplementedPongGameServer) StartGameStream(*StartGameStreamRequest, grpc.ServerStreamingServer[GameUpdateBytes]) error {
	return status.Errorf(codes.Unimplemented, "method StartGameStream not implemented")
}
func (UnimplementedPongGameServer) StartNtfnStream(*StartNtfnStreamRequest, grpc.ServerStreamingServer[NtfnStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StartNtfnStream not implemented")
}
func (UnimplementedPongGameServer) UnreadyGameStream(context.Context, *UnreadyGameStreamRequest) (*UnreadyGameStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnreadyGameStream not implemented")
}
func (UnimplementedPongGameServer) SignalReadyToPlay(context.Context, *SignalReadyToPlayRequest) (*SignalReadyToPlayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalReadyToPlay not implemented")
}
func (UnimplementedPongGameServer) mustEmbedUnimplementedPongGameServer() {}
func (UnimplementedPongGameServer) testEmbeddedByValue()                  {}

// UnsafePongGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PongGameServer will
// result in compilation errors.
type UnsafePongGameServer interface {
	mustEmbedUnimplementedPongGameServer()
}

func RegisterPongGameServer(s grpc.ServiceRegistrar, srv PongGameServer) {
	// If the following call pancis, it indicates UnimplementedPongGameServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PongGame_ServiceDesc, srv)
}

func _PongGame_SendInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongGameServer).SendInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PongGame_SendInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongGameServer).SendInput(ctx, req.(*PlayerInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _PongGame_StartGameStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartGameStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PongGameServer).StartGameStream(m, &grpc.GenericServerStream[StartGameStreamRequest, GameUpdateBytes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PongGame_StartGameStreamServer = grpc.ServerStreamingServer[GameUpdateBytes]

func _PongGame_StartNtfnStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartNtfnStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PongGameServer).StartNtfnStream(m, &grpc.GenericServerStream[StartNtfnStreamRequest, NtfnStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PongGame_StartNtfnStreamServer = grpc.ServerStreamingServer[NtfnStreamResponse]

func _PongGame_UnreadyGameStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnreadyGameStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongGameServer).UnreadyGameStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PongGame_UnreadyGameStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongGameServer).UnreadyGameStream(ctx, req.(*UnreadyGameStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PongGame_SignalReadyToPlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalReadyToPlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongGameServer).SignalReadyToPlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PongGame_SignalReadyToPlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongGameServer).SignalReadyToPlay(ctx, req.(*SignalReadyToPlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PongGame_ServiceDesc is the grpc.ServiceDesc for PongGame service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PongGame_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pong.PongGame",
	HandlerType: (*PongGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendInput",
			Handler:    _PongGame_SendInput_Handler,
		},
		{
			MethodName: "UnreadyGameStream",
			Handler:    _PongGame_UnreadyGameStream_Handler,
		},
		{
			MethodName: "SignalReadyToPlay",
			Handler:    _PongGame_SignalReadyToPlay_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartGameStream",
			Handler:       _PongGame_StartGameStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StartNtfnStream",
			Handler:       _PongGame_StartNtfnStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pong.proto",
}

const (
	PongWaitingRoom_GetWaitingRoom_FullMethodName    = "/pong.PongWaitingRoom/GetWaitingRoom"
	PongWaitingRoom_GetWaitingRooms_FullMethodName   = "/pong.PongWaitingRoom/GetWaitingRooms"
	PongWaitingRoom_CreateWaitingRoom_FullMethodName = "/pong.PongWaitingRoom/CreateWaitingRoom"
	PongWaitingRoom_JoinWaitingRoom_FullMethodName   = "/pong.PongWaitingRoom/JoinWaitingRoom"
	PongWaitingRoom_LeaveWaitingRoom_FullMethodName  = "/pong.PongWaitingRoom/LeaveWaitingRoom"
)

// PongWaitingRoomClient is the client API for PongWaitingRoom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PongWaitingRoomClient interface {
	// waiting room
	GetWaitingRoom(ctx context.Context, in *WaitingRoomRequest, opts ...grpc.CallOption) (*WaitingRoomResponse, error)
	GetWaitingRooms(ctx context.Context, in *WaitingRoomsRequest, opts ...grpc.CallOption) (*WaitingRoomsResponse, error)
	CreateWaitingRoom(ctx context.Context, in *CreateWaitingRoomRequest, opts ...grpc.CallOption) (*CreateWaitingRoomResponse, error)
	JoinWaitingRoom(ctx context.Context, in *JoinWaitingRoomRequest, opts ...grpc.CallOption) (*JoinWaitingRoomResponse, error)
	LeaveWaitingRoom(ctx context.Context, in *LeaveWaitingRoomRequest, opts ...grpc.CallOption) (*LeaveWaitingRoomResponse, error)
}

type pongWaitingRoomClient struct {
	cc grpc.ClientConnInterface
}

func NewPongWaitingRoomClient(cc grpc.ClientConnInterface) PongWaitingRoomClient {
	return &pongWaitingRoomClient{cc}
}

func (c *pongWaitingRoomClient) GetWaitingRoom(ctx context.Context, in *WaitingRoomRequest, opts ...grpc.CallOption) (*WaitingRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitingRoomResponse)
	err := c.cc.Invoke(ctx, PongWaitingRoom_GetWaitingRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pongWaitingRoomClient) GetWaitingRooms(ctx context.Context, in *WaitingRoomsRequest, opts ...grpc.CallOption) (*WaitingRoomsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitingRoomsResponse)
	err := c.cc.Invoke(ctx, PongWaitingRoom_GetWaitingRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pongWaitingRoomClient) CreateWaitingRoom(ctx context.Context, in *CreateWaitingRoomRequest, opts ...grpc.CallOption) (*CreateWaitingRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWaitingRoomResponse)
	err := c.cc.Invoke(ctx, PongWaitingRoom_CreateWaitingRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pongWaitingRoomClient) JoinWaitingRoom(ctx context.Context, in *JoinWaitingRoomRequest, opts ...grpc.CallOption) (*JoinWaitingRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinWaitingRoomResponse)
	err := c.cc.Invoke(ctx, PongWaitingRoom_JoinWaitingRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pongWaitingRoomClient) LeaveWaitingRoom(ctx context.Context, in *LeaveWaitingRoomRequest, opts ...grpc.CallOption) (*LeaveWaitingRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveWaitingRoomResponse)
	err := c.cc.Invoke(ctx, PongWaitingRoom_LeaveWaitingRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PongWaitingRoomServer is the server API for PongWaitingRoom service.
// All implementations must embed UnimplementedPongWaitingRoomServer
// for forward compatibility.
type PongWaitingRoomServer interface {
	// waiting room
	GetWaitingRoom(context.Context, *WaitingRoomRequest) (*WaitingRoomResponse, error)
	GetWaitingRooms(context.Context, *WaitingRoomsRequest) (*WaitingRoomsResponse, error)
	CreateWaitingRoom(context.Context, *CreateWaitingRoomRequest) (*CreateWaitingRoomResponse, error)
	JoinWaitingRoom(context.Context, *JoinWaitingRoomRequest) (*JoinWaitingRoomResponse, error)
	LeaveWaitingRoom(context.Context, *LeaveWaitingRoomRequest) (*LeaveWaitingRoomResponse, error)
	mustEmbedUnimplementedPongWaitingRoomServer()
}

// UnimplementedPongWaitingRoomServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPongWaitingRoomServer struct{}

func (UnimplementedPongWaitingRoomServer) GetWaitingRoom(context.Context, *WaitingRoomRequest) (*WaitingRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWaitingRoom not implemented")
}
func (UnimplementedPongWaitingRoomServer) GetWaitingRooms(context.Context, *WaitingRoomsRequest) (*WaitingRoomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWaitingRooms not implemented")
}
func (UnimplementedPongWaitingRoomServer) CreateWaitingRoom(context.Context, *CreateWaitingRoomRequest) (*CreateWaitingRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWaitingRoom not implemented")
}
func (UnimplementedPongWaitingRoomServer) JoinWaitingRoom(context.Context, *JoinWaitingRoomRequest) (*JoinWaitingRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinWaitingRoom not implemented")
}
func (UnimplementedPongWaitingRoomServer) LeaveWaitingRoom(context.Context, *LeaveWaitingRoomRequest) (*LeaveWaitingRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveWaitingRoom not implemented")
}
func (UnimplementedPongWaitingRoomServer) mustEmbedUnimplementedPongWaitingRoomServer() {}
func (UnimplementedPongWaitingRoomServer) testEmbeddedByValue()                         {}

// UnsafePongWaitingRoomServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PongWaitingRoomServer will
// result in compilation errors.
type UnsafePongWaitingRoomServer interface {
	mustEmbedUnimplementedPongWaitingRoomServer()
}

func RegisterPongWaitingRoomServer(s grpc.ServiceRegistrar, srv PongWaitingRoomServer) {
	// If the following call pancis, it indicates UnimplementedPongWaitingRoomServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PongWaitingRoom_ServiceDesc, srv)
}

func _PongWaitingRoom_GetWaitingRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitingRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongWaitingRoomServer).GetWaitingRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PongWaitingRoom_GetWaitingRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongWaitingRoomServer).GetWaitingRoom(ctx, req.(*WaitingRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PongWaitingRoom_GetWaitingRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitingRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongWaitingRoomServer).GetWaitingRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PongWaitingRoom_GetWaitingRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongWaitingRoomServer).GetWaitingRooms(ctx, req.(*WaitingRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PongWaitingRoom_CreateWaitingRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWaitingRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongWaitingRoomServer).CreateWaitingRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PongWaitingRoom_CreateWaitingRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongWaitingRoomServer).CreateWaitingRoom(ctx, req.(*CreateWaitingRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PongWaitingRoom_JoinWaitingRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinWaitingRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongWaitingRoomServer).JoinWaitingRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PongWaitingRoom_JoinWaitingRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongWaitingRoomServer).JoinWaitingRoom(ctx, req.(*JoinWaitingRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PongWaitingRoom_LeaveWaitingRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveWaitingRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongWaitingRoomServer).LeaveWaitingRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PongWaitingRoom_LeaveWaitingRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongWaitingRoomServer).LeaveWaitingRoom(ctx, req.(*LeaveWaitingRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PongWaitingRoom_ServiceDesc is the grpc.ServiceDesc for PongWaitingRoom service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PongWaitingRoom_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pong.PongWaitingRoom",
	HandlerType: (*PongWaitingRoomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWaitingRoom",
			Handler:    _PongWaitingRoom_GetWaitingRoom_Handler,
		},
		{
			MethodName: "GetWaitingRooms",
			Handler:    _PongWaitingRoom_GetWaitingRooms_Handler,
		},
		{
			MethodName: "CreateWaitingRoom",
			Handler:    _PongWaitingRoom_CreateWaitingRoom_Handler,
		},
		{
			MethodName: "JoinWaitingRoom",
			Handler:    _PongWaitingRoom_JoinWaitingRoom_Handler,
		},
		{
			MethodName: "LeaveWaitingRoom",
			Handler:    _PongWaitingRoom_LeaveWaitingRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pong.proto",
}

const (
	PongReferee_OpenEscrow_FullMethodName        = "/pong.PongReferee/OpenEscrow"
	PongReferee_SettlementStream_FullMethodName  = "/pong.PongReferee/SettlementStream"
	PongReferee_GetFinalizeBundle_FullMethodName = "/pong.PongReferee/GetFinalizeBundle"
)

// PongRefereeClient is the client API for PongReferee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Referee service coordinating escrow and settlement
type PongRefereeClient interface {
	// Escrow-first funding
	OpenEscrow(ctx context.Context, in *OpenEscrowRequest, opts ...grpc.CallOption) (*OpenEscrowResponse, error)
	// SettlementStream streams the settlement process
	SettlementStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMsg, ServerMsg], error)
	// Winner fetches gamma and both presigs to finalize the exact winning draft
	GetFinalizeBundle(ctx context.Context, in *GetFinalizeBundleRequest, opts ...grpc.CallOption) (*GetFinalizeBundleResponse, error)
}

type pongRefereeClient struct {
	cc grpc.ClientConnInterface
}

func NewPongRefereeClient(cc grpc.ClientConnInterface) PongRefereeClient {
	return &pongRefereeClient{cc}
}

func (c *pongRefereeClient) OpenEscrow(ctx context.Context, in *OpenEscrowRequest, opts ...grpc.CallOption) (*OpenEscrowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenEscrowResponse)
	err := c.cc.Invoke(ctx, PongReferee_OpenEscrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pongRefereeClient) SettlementStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMsg, ServerMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PongReferee_ServiceDesc.Streams[0], PongReferee_SettlementStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMsg, ServerMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PongReferee_SettlementStreamClient = grpc.BidiStreamingClient[ClientMsg, ServerMsg]

func (c *pongRefereeClient) GetFinalizeBundle(ctx context.Context, in *GetFinalizeBundleRequest, opts ...grpc.CallOption) (*GetFinalizeBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFinalizeBundleResponse)
	err := c.cc.Invoke(ctx, PongReferee_GetFinalizeBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PongRefereeServer is the server API for PongReferee service.
// All implementations must embed UnimplementedPongRefereeServer
// for forward compatibility.
//
// Referee service coordinating escrow and settlement
type PongRefereeServer interface {
	// Escrow-first funding
	OpenEscrow(context.Context, *OpenEscrowRequest) (*OpenEscrowResponse, error)
	// SettlementStream streams the settlement process
	SettlementStream(grpc.BidiStreamingServer[ClientMsg, ServerMsg]) error
	// Winner fetches gamma and both presigs to finalize the exact winning draft
	GetFinalizeBundle(context.Context, *GetFinalizeBundleRequest) (*GetFinalizeBundleResponse, error)
	mustEmbedUnimplementedPongRefereeServer()
}

// UnimplementedPongRefereeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPongRefereeServer struct{}

func (UnimplementedPongRefereeServer) OpenEscrow(context.Context, *OpenEscrowRequest) (*OpenEscrowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenEscrow not implemented")
}
func (UnimplementedPongRefereeServer) SettlementStream(grpc.BidiStreamingServer[ClientMsg, ServerMsg]) error {
	return status.Errorf(codes.Unimplemented, "method SettlementStream not implemented")
}
func (UnimplementedPongRefereeServer) GetFinalizeBundle(context.Context, *GetFinalizeBundleRequest) (*GetFinalizeBundleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFinalizeBundle not implemented")
}
func (UnimplementedPongRefereeServer) mustEmbedUnimplementedPongRefereeServer() {}
func (UnimplementedPongRefereeServer) testEmbeddedByValue()                     {}

// UnsafePongRefereeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PongRefereeServer will
// result in compilation errors.
type UnsafePongRefereeServer interface {
	mustEmbedUnimplementedPongRefereeServer()
}

func RegisterPongRefereeServer(s grpc.ServiceRegistrar, srv PongRefereeServer) {
	// If the following call pancis, it indicates UnimplementedPongRefereeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PongReferee_ServiceDesc, srv)
}

func _PongReferee_OpenEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongRefereeServer).OpenEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PongReferee_OpenEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongRefereeServer).OpenEscrow(ctx, req.(*OpenEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PongReferee_SettlementStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PongRefereeServer).SettlementStream(&grpc.GenericServerStream[ClientMsg, ServerMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PongReferee_SettlementStreamServer = grpc.BidiStreamingServer[ClientMsg, ServerMsg]

func _PongReferee_GetFinalizeBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFinalizeBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongRefereeServer).GetFinalizeBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PongReferee_GetFinalizeBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongRefereeServer).GetFinalizeBundle(ctx, req.(*GetFinalizeBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PongReferee_ServiceDesc is the grpc.ServiceDesc for PongReferee service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PongReferee_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pong.PongReferee",
	HandlerType: (*PongRefereeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenEscrow",
			Handler:    _PongReferee_OpenEscrow_Handler,
		},
		{
			MethodName: "GetFinalizeBundle",
			Handler:    _PongReferee_GetFinalizeBundle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SettlementStream",
			Handler:       _PongReferee_SettlementStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pong.proto",
}
